name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master  # or master, adjust as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # adjust if needed

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          pip install jupyter

      - name: Install Bundler dependencies
        run: bundle install

      - name: Build the site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
